version: '3.8'

services:
  api-gateway:
    image: 'leobang/api-gateway'
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: 'no'
    networks:
      - hedwig-server-dev

  auth:
    image: 'leobang/auth'
    container_name: auth
    env_file:
      - .env
    ports:
      - '3001:3000'
    restart: 'no'
    networks:
      - hedwig-server-dev

  inbox:
    image: 'leobang/inbox'
    container_name: inbox
    env_file:
      - .env
    ports:
      - '3002:3000'
    restart: 'no'
    networks:
      - hedwig-server-dev

  user:
    image: 'leobang/user'
    container_name: user
    env_file:
      - .env
    ports:
      - '3003:3000'
    restart: 'no'
    networks:
      - hedwig-server-dev

  mail-integrator:
    image: 'leobang/mail-integrator'
    container_name: mail-integrator
    env_file:
      - .env
    ports:
      - '3004:3000'
    restart: 'no'
    networks:
      - hedwig-server-dev

networks:
  hedwig-server-dev:
    driver: bridge
