version: '3.8'

services:
  api-gateway:
    image: 'leobang/api-gateway'
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: 'no'

  auth:
    image: 'leobang/auth'
    container_name: auth
    env_file:
      - .env
    ports:
      - '3001:3000'
    restart: 'no'

  inbox:
    image: 'leobang/inbox'
    container_name: inbox
    env_file:
      - .env
    ports:
      - '3002:3000'
    restart: 'no'

  user:
    image: 'leobang/user'
    container_name: user
    env_file:
      - .env
    ports:
      - '3003:3000'
    restart: 'no'
