version: '3.8'

services:
  api-gateway:
    image: 'leobang/api-gateway'
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: 'no'

  auth:
    image: 'leobang/auth'
    container_name: auth
    env_file:
      - .env
    ports:
      - '3001:3000'
    restart: 'no'
