version: '3.8'

services:
  auth:
    image: 'hedwig/auth'
    build:
      context: .
      dockerfile: ./apps/Dockerfile.app
      args:
        - PKG_NAME=@apps/auth
        - PORT=3000
    container_name: auth
    ports:
      - '3000:3000'
    restart: 'no'

  mail-integrator:
    image: 'hedwig/mail-integrator'
    build:
      context: .
      dockerfile: ./apps/Dockerfile.app
      args:
        - PKG_NAME=@apps/mail-integrator
        - PORT=3000
        - HOST=127.0.0.1
    container_name: mail-integrator
    ports:
      - '3001:3000'
    restart: 'no'
