version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hedwig-database-dev
    env_file:
      - .database.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - .infra/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - hedwig-database-dev

networks:
  hedwig-server-dev:
    driver: bridge
