name: database-deploy

on:
  push:
    branches:
      - test/docker-mysql

jobs:
  pull-n-run-docker-compose:
    name: Deploy MySQL Container with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy docker-compose file to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docker-compose.yml
          remote: /home/ubuntu/docker-compose.yml
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}

      - name: Copy MySQL init scripts to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .infra/mysql-init/
          remote: /home/ubuntu/.infra/mysql-init/
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}

      - name: Access remote server via SSH and run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 22
          script: |
            docker-compose -f /home/ubuntu/docker-compose.yml down
            docker-compose -f /home/ubuntu/docker-compose.yml pull
            docker-compose -f /home/ubuntu/docker-compose.yml up -d
